### ISSUE TITLE
Set `main` branch protection rules

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-NRI/replace_landsurface#16]
To be done after #18 is completed.

There are currently no protection rules in place for the `main` branch.

The ones I would implement are:
- Require a pull request before merging (with required approvals)
- Require status checks to pass before merging (for future CI)
- Require conversation resolution before merging
- Require signed commits

**Comment by CodeGat** [comment]
Ruleset created: https://github.com/ACCESS-NRI/replace_landsurface/settings/rules
However, I couldn't create the status checks one because you need to select a specific workflow that is a required check, so I've left that one for now.
