### ISSUE TITLE
Make repo public

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-NRI/replace_landsurface#18]
Due to restrictions in place (e.g. branch protection rules) for private repos, and to be as open as possible, we should [make this repo public](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility#changing-a-repositorys-visibility).

- [ ] Change visibility of repo to `Public`.

**Comment by penguian** [comment]
Done.
